### ISSUE TITLE
error variable not bound

### ISSUE THREAD

**Issue by mrendu43** [aka13-404/VSETT-LISP#4]
after loading script to vesc i get error
Parsing 11461 characters
***   Error: variable_not_bound
***   In:    counter
***   After: 1
and
Reason:
   Variable not bound.

***   Error: variable_not_bound
***   In:    crc
***   After: 0

**Comment by aka13-404** [comment]
Yeah, I know, some stuff got changed in the latest 6.05 beta, thank you for the reply. 
I don't have a running controller rn, sadly, I'll write here when I fix it.

**Comment by aka13-404** [comment]
This was fixed.
